In [2]:
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

from sklearn.preprocessing import LabelEncoder
import multilayerPerceptron

# Iris Data Set

## Подготовка данных

In [3]:
dataframe = pd.read_csv("iris.csv")

In [4]:
dataframe

5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [5]:
dataset = dataframe.values

In [8]:
X = dataset[:, 0:4]
Y = dataset[:, 4]

In [9]:
# Iris-setosa кодируется как класс 0
# Iris-versicolor – класс 1 
# Iris-virginica как класс 2 
encoder = LabelEncoder()
encoder.fit(Y)
y = encoder.transform(Y)

In [10]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y)

In [12]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [13]:
X_train.shape

(104, 4)

##  Классификация MLP

In [14]:
mlp = multilayerPerceptron.NeuralNetMLP(3, 4).fit(X_train, y_train)

In [15]:
y_pred = mlp.predict(X_test)

In [16]:
y_pred

array([1, 0, 1, 2, 0, 2, 0, 2, 1, 2, 0, 1, 2, 1, 0, 2, 0, 2, 0, 0, 0, 2,
       0, 2, 2, 0, 1, 1, 0, 1, 1, 1, 1, 2, 2, 1, 0, 2, 1, 1, 2, 0, 0, 2,
       2], dtype=int64)

In [17]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[15  0  0]
 [ 0 13  2]
 [ 0  1 14]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.93      0.87      0.90        15
           2       0.88      0.93      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



#  Titanik DataSet

## Подготовка данных

In [3]:
dataframe = pd.read_csv("titanic.csv")

In [4]:
dataframe

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [5]:
dataframe.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1,inplace=True)
dataframe.fillna(dataframe.mean(), inplace=True)
dataframe

Survived  Pclass     Sex        Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.000000      1      0   7.2500        S
1           1       1  female  38.000000      1      0  71.2833        C
2           1       3  female  26.000000      0      0   7.9250        S
3           1       1  female  35.000000      1      0  53.1000        S
4           0       3    male  35.000000      0      0   8.0500        S
..        ...     ...     ...        ...    ...    ...      ...      ...
886         0       2    male  27.000000      0      0  13.0000        S
887         1       1  female  19.000000      0      0  30.0000        S
888         0       3  female  29.699118      1      2  23.4500        S
889         1       1    male  26.000000      0      0  30.0000        C
890         0       3    male  32.000000      0      0   7.7500        Q

[891 rows x 8 columns]

In [6]:
# male кодируется как класс 0
# female – класс 1 
encoder = LabelEncoder()
encoder.fit(dataframe['Sex'])
dataframe['Sex'] = encoder.transform(dataframe['Sex'])

In [7]:
# C кодируется как класс 0
# Q – класс 1 
# S – класс 2 
encoder = LabelEncoder()
encoder.fit(dataframe['Embarked'])
dataframe['Embarked'] = encoder.transform(dataframe['Embarked'])

In [19]:
y = dataframe['Survived']
X = dataframe[dataframe.columns[1:dataframe.shape[0]]]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)
X_train = X_train.numpy()

180    0
59     0
170    0
846    0
852    0
      ..
1      1
322    1
129    0
136    1
160    0
Name: Survived, Length: 668, dtype: int64

In [11]:
print(X)

     Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0         3    1  22.000000      1      0   7.2500         2
1         1    0  38.000000      1      0  71.2833         0
2         3    0  26.000000      0      0   7.9250         2
3         1    0  35.000000      1      0  53.1000         2
4         3    1  35.000000      0      0   8.0500         2
..      ...  ...        ...    ...    ...      ...       ...
886       2    1  27.000000      0      0  13.0000         2
887       1    0  19.000000      0      0  30.0000         2
888       3    0  29.699118      1      2  23.4500         2
889       1    1  26.000000      0      0  30.0000         0
890       3    1  32.000000      0      0   7.7500         1

[891 rows x 7 columns]


## Классификация MLP

In [ ]:
mlp = multilayerPerceptron.NeuralNetMLP(2, 7).fit(X_train, y_train)

In [81]:
dataframe.to_csv('file1.csv')

# My DataSet

## Подготовка данных

In [111]:
df = pd.read_csv('Energy_efficiency_Data_Set_preprocessed.csv', decimal=",") 

In [112]:
df.head(10)

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28
5  0.90  563.5  318.5  122.50  7.0   3  0.0   0  21.46  25.38
6  0.90  563.5  318.5  122.50  7.0   4  0.0   0  20.71  25.16
7  0.90  563.5  318.5  122.50  7.0   5  0.0   0  19.68  29.60
8  0.86  588.0  294.0  147.00  7.0   2  0.0   0  19.50  27.30
9  0.86  588.0  294.0  147.00  7.0   3  0.0   0  19.95  21.97

In [113]:
high = df.Y1 >= 20
low = df.Y1 < 20
df.loc[high,'Y1'] = 1
df.loc[low,'Y1'] = 0

high2 = df.Y2 >= 20
low2 = df.Y2 < 20
df.loc[high2,'Y2'] = 1
df.loc[low2,'Y2'] = 0
df = df.astype({'Y1' : np.int64, 'Y2' : np.int64})

In [114]:
df.head()

X1     X2     X3      X4   X5  X6   X7  X8  Y1  Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0   0   1
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0   0   1
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0   0   1
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0   0   1
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0   1   1

In [115]:
print (df.shape, X.shape, y.shape)

(768, 10) (149, 4) (149,)


In [116]:
df.dtypes

X1    float64
X2    float64
X3    float64
X4    float64
X5    float64
X6      int64
X7    float64
X8      int64
Y1      int64
Y2      int64
dtype: object

In [117]:
x = df.drop(columns=['Y1','Y2'])
y1 = df['Y1']

std = StandardScaler()
x_scaled = std.fit(x).transform(x)

In [118]:
X1_train, X1_test, y1_train, y1_test = train_test_split(x_scaled, y1, test_size=0.20)

## Классификация MLP

In [119]:
X1_train

array([[-1.17461286,  1.27562492,  0.56195149, ..., -0.4472136 ,
        -1.00932293, -0.5242106 ],
       [-0.22861593,  0.16235226, -1.68585446, ...,  0.4472136 ,
         1.2440492 ,  0.76615395],
       [-0.98541347,  0.99730676,  0.        , ...,  0.4472136 ,
         0.11736313, -1.16939287],
       ...,
       [-1.17461286,  1.27562492,  0.56195149, ...,  1.34164079,
         0.11736313,  1.41133622],
       [-1.36381225,  1.55394308,  1.12390297, ...,  0.4472136 ,
        -1.00932293,  0.12097168],
       [-0.51241501,  0.44067043, -1.12390297, ..., -1.34164079,
        -1.00932293, -1.16939287]])

In [120]:
mlp = multilayerPerceptron.NeuralNetMLP(2, 8).fit(X1_train, y1_train)

In [121]:
y_pred = mlp.predict(X1_test)

In [122]:
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
      dtype=int64)

In [124]:
print(confusion_matrix(y1_test, y_pred))
print(classification_report(y1_test, y_pred))

[[77  5]
 [ 0 72]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97        82
           1       0.94      1.00      0.97        72

    accuracy                           0.97       154
   macro avg       0.97      0.97      0.97       154
weighted avg       0.97      0.97      0.97       154

